### ISSUE TITLE
Change color for countries that receive datapackets, hard to distinguish from background color

### ISSUE THREAD

**Issue by TUClemens** [Softwareprojekt2015/Softwareprojekt2015#15]
After debugging, UK is greyed out and not orange like every other country.

**Comment by dennistreysa** [comment]
Cant reproduce! Maybe Opacity is set to ~ 3% and thus the grey background is shining through.

**Comment by TUClemens** [comment]
I can't reproduce it either, maybe it was just a visual bug.

**Comment by TUClemens** [comment]
Just tried the latest release and now Ireland is grey instead of orange.
[Image](https://cloud.githubusercontent.com/assets/11396876/8204354/4a2232e6-14e8-11e5-8ede-4abc5ed98ac2.PNG)

**Comment by TUClemens** [comment]
It is just a visual bug. The country is colored, but is hard to distinguish between this color and the background color.

**Comment by TuMartin** [comment]
Fixed
