### ISSUE TITLE
Release does not contain binary / installer / exe

### ISSUE THREAD

**Issue by ChristophBodenstein** [Softwareprojekt2015/Softwareprojekt2015#18]
Alpha Release v0.1 had an installer but did not work on every computer.
The last two releases only contain source code.
That's not very comfortable for the rest of us ;-)

**Comment by TUClemens** [comment]
A zip file with a working exe has been attached to the latest release. You can find it [here](https://github.com/Softwareprojekt2015/NSA4Dummies/releases/tag/v0.2.1-alpha).
